runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: forum.app

- url: /index\.html
  script: forum.app

- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))$
  static_file: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /admin/.*
  script: admin.app
  login: admin

- url: /.*
  script: not_found.app

